### ISSUE TITLE
Best expected shapes for each model

### ISSUE THREAD

**Issue by macsunmood** [leondgarse/keras_efficientnet_v2#11]
Are there best expected shapes for each of the models (as can be found for EfficientNet V1, e.g. https://keras.io/examples/vision/image_classification_efficientnet_fine_tuning/) or could they be figured out? If so, would be useful to document it, at least with some README table.

**Comment by leondgarse** [comment]
Ya, they are list in the [official code](https://github.com/google/automl/blob/master/efficientnetv2/effnetv2_configs.py), and I'm using the `eval_size` as default `input_shape`.
I'v updated readme on [training-detail-from-article](https://github.com/leondgarse/keras_efficientnet_v2#training-detail-from-article) part, and also added those info in each model's help doc, both v1 and v2.

**Comment by leondgarse** [comment]
Ok, now they are in the summary part, crowded all them there.

**Comment by macsunmood** [comment]
Great, thanks!
