### ISSUE TITLE
Dead link to model "Imagenet" for EffV2XL

### ISSUE THREAD

**Issue by DennisMedved** [leondgarse/keras_efficientnet_v2#13]
Thanks for the nice job on implementing the EffNet-models!

I tried to use the EffV2XL model; but the link to the model "Imagenet" doesn't not seem to work.

https://github.com/leondgarse/keras_efficientnet_v2/releases/download/effnetv2_pretrained/efficientnetv2-xl-imagenet.h5

It doesn't seem to be in the release:
https://github.com/leondgarse/keras_efficientnet_v2/releases/

Best regards,
Dennis

**Comment by leondgarse** [comment]
Right, we don't have EffV2XL on imagenet, as it's not provided from official. I forgot that link..
Just updated and set default `pretrained="imagenet21k-ft1k"` for `EffV2XL`.

**Comment by DennisMedved** [comment]
Thank you! :)

What is the difference between "ImageNet21K" and "Imagenet21k-ft1k"?

I could not find any documentation on it.

**Comment by leondgarse** [comment]
`ImageNet21K` is the raw model pre-trained on `ImageNet21K` dataset. The expected output `num_classes` should be `21843`.
`Imagenet21k-ft1k` means the `ImageNet21K` model fine-tuned on `imagenet`, and its expected output `num_classes` is `1000`, same with `imagenet` model. It's also called `ImageNet22K` somewhere.
