### ISSUE TITLE
no setup.py when pip install

### ISSUE THREAD

**Issue by emoen** [leondgarse/keras_efficientnet_v2#6]
when running the command: pip install -U git+https://github.com/leondgarse/Keras_efficientnet_v2
I get error:
Collecting git+https://github.com/leondgarse/Keras_efficientnet_v2
  Cloning https://github.com/leondgarse/Keras_efficientnet_v2 to /tmp/pip-req-build-ieopxsj5
  Running command git clone -q https://github.com/leondgarse/Keras_efficientnet_v2 /tmp/pip-req-build-ieopxsj5
  Resolved https://github.com/leondgarse/Keras_efficientnet_v2 to commit 341d2b6a1d8026315a1ec80aba956ca3f4987401
ERROR: **File "setup.py" not found for legacy project git+https://github.com/leondgarse/Keras_efficientnet_v2.**

**Comment by leondgarse** [comment]
You can try it again now.
I used to set `sys.path.append(THIS_PATH)` and then import it in other projects.
Make it a package, I have to create a sub directory.

**Comment by emoen** [comment]
I get a new error:
ERROR: Could not find a version that satisfies the requirement automlpip (from versions: none)
ERROR: No matching distribution found for automlpip

**Comment by leondgarse** [comment]
I didn't meet that, and why `automl` is reported? It's not in my `install_requires`, and only used in calling `convert_effnetv2_model.py`.
Whats your commands?

**Comment by leondgarse** [comment]
If you are trying to run `convert_effnetv2_model.py`, you can do as following:
```sh
git clone https://github.com/google/automl.git
git clone https://github.com/leondgarse/Keras_efficientnet_v2.git
cd Keras_efficientnet_v2

# Then run the convert command
CUDA_VISIBLE_DEVICES='-1' python Keras_efficientnet_v2/convert_effnetv2_model.py -h
```
But ATM, it's not necessary, as all pretrained model weights have been uploaded here. I just added this script explaining how it's converted, and in case of there maybe changes in the future.

**Comment by emoen** [comment]
I tried running: pip install -U git+https://github.com/leondgarse/Keras_efficientnet_v2

**Comment by leondgarse** [comment]
Not sure about your issue then. This is mine:
![Selection_388](https://user-images.githubusercontent.com/5744524/127304594-622fed53-1f73-4ad9-8c68-eba783bc0d7e.png)
